# Generated by Django 3.2.4 on 2023-11-19 05:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('rollnumber', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
