# Generated by Django 3.2.4 on 2023-12-07 09:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=255)),
                ('washrooms', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='test',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='rollnumber',
            field=models.IntegerField(null=True),
        ),
    ]
