# Generated by Django 3.2.4 on 2023-12-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20231207_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='homename',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
