# Generated by Django 3.2.4 on 2023-12-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_home_homename'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='kitchen',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
