# Generated by Django 3.2.4 on 2023-12-07 09:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_home_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='description1',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
