# Generated by Django 3.2.4 on 2023-12-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_students_description1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='description1',
        ),
    ]
