# Generated by Django 3.2.4 on 2023-12-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_students_description1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
