# Generated by Django 3.2.4 on 2023-12-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
