# Generated by Django 3.2.4 on 2023-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20231212_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('product_pechase_price', models.CharField(max_length=255)),
                ('product_sale_price', models.CharField(max_length=255)),
            ],
        ),
    ]
