# Generated by Django 3.2.4 on 2023-12-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_pechase_price',
            new_name='product_perchase_price',
        ),
    ]
