# Generated by Django 3.2.4 on 2023-12-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
