# Generated by Django 3.2.4 on 2023-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_rename_category_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
