# Generated by Django 3.2.4 on 2023-12-19 06:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('contact', models.IntegerField(null=True)),
                ('description', tinymce.models.HTMLField(null=True)),
            ],
        ),
    ]
