# Generated by Django 3.2.4 on 2023-12-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_supplirs_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplirs',
            new_name='Suppliers',
        ),
    ]
