# Generated by Django 5.0 on 2023-12-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_products_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
        migrations.AddField(
            model_name='employees',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
