# Generated by Django 5.0 on 2023-12-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_category_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_status',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
