# Generated by Django 5.0 on 2023-12-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_cart_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
