# Generated by Django 5.0 on 2024-01-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=255)),
                ('custname', models.CharField(max_length=255)),
                ('custcont', models.CharField(max_length=255)),
                ('sale', models.CharField(max_length=255)),
                ('tamount', models.FloatField()),
                ('disc', models.FloatField()),
                ('netpay', models.FloatField()),
            ],
        ),
    ]
