# Generated by Django 5.0 on 2024-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='in_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
