# Generated by Django 5.0 on 2024-01-19 07:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_products_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='username', unique=True),
        ),
    ]
