# Generated by Django 5.0 on 2024-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_rename_product_slug_users_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_image',
            field=models.FileField(default=None, max_length=256, null=True, upload_to='userpics/'),
        ),
    ]
